### ISSUE TITLE
Cannot add foreign key constraint in Laravel 5.8

### ISSUE THREAD

**Issue by stephenjude** [cleaniquecoders/attendance#3]
`
 Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `attendances` add constraint `attendances_user_id_foreign` foreign key (`user_id`) references `users` (`id`))

  at C:\laragon\www\Attendance\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint")
      C:\laragon\www\Prep50Attendance\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119

  2   PDOException::("SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint")
      C:\laragon\www\Prep50Attendance\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117
`

**Comment by dinodevtutorio** [comment]
hi, are you able to resolve this issue?

**Comment by nasrulhazim** [comment]
this is probably due to Laravel 5.8 using big increments in users table.

**Comment by stephenjude** [comment]
Yeah. I have fixed it already.
